name: glitch
description: Canvas glitch demo

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  charts_flutter: ^0.5.0
  flutter:
    sdk: flutter
  flutter_svg: ^0.10.3

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
